AppCofidurBundle\Entity\User:
    type: entity
    table: fos_user
    repositoryClass: AppCofidurBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
